### ISSUE TITLE
Variables in page.svelte are confusing

### ISSUE THREAD

**Issue by Khufu-I** [Vithop/TicTacToe#1]
Consider more informative variable names in [+page.svelte](https://github.com/Vithop/TicTacToe/blob/e72891ad4416e4a701f1e8aa49fa47fefd1da698/src/routes/TicTacToe/+page.svelte) to make it more maintainable.

**Comment by Vithop** [comment]
but it's tic tac toes !

**Comment by Khufu-I** [comment]
Fixed in 905075542e0b7d55154fed2f0e5906ebeb6b973c
